spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:mysql://172.30.1.108:3306/turkey_jjlee?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: atech
    password: dpdlxpzm1221!@
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      username: atech
#      password: dpdlxpzm1221!@
#      maximum-pool-size: 2

---

# 메일 전송 설정
spring:
  mail:
    host: ezsmtp.bizmeka.com
    port: 25
    username: 임시
    password: 임시
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

# 파일 전송 설정
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

---

# 스프링 시큐리티 타임아웃 설정
server:
  servlet:
    session:
      timeout: 3600

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: test

---

spring:
  profiles:
    active: dev