spring:
  datasource:
    url: jdbc:mysql://172.30.1.108:3306/turkey?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: atech
    password: dpdlxpzm1221!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: testtt123443211234
server:
  port: 80